### ISSUE TITLE
Improve your Action by adding labels for icon and color.

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/github-fe-oss-project-template#2]
# Improve your Action by adding labels for icon and color.

## bug ❌

![image](https://user-images.githubusercontent.com/7291672/184550099-1fda1d32-9b3a-4cdc-8e41-2c1cb8d0fc74.png)

## solution ✅

```yml
# fix: Improve your Action by adding labels for icon and color.
branding:
  icon: 'type'
  color: 'blue'
```

https://github.com/benchmark-action/github-action-benchmark/blob/master/action.yml#L4-L6
