### ISSUE TITLE
github actions inputs All In One

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/github-fe-oss-project-template#3]
# github actions inputs All In One

✅ 定义可以接收的输入参数名称: name ghToken

✅使用 with 传递参数给 action.yml

https://github.com/xgqfrms/github-fe-oss-project-template/runs/7835867287?check_suite_focus=true

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/7291672/184616511-087e02f3-a255-4baf-85cb-c381d307c0ef.png">

<img width="918" alt="image" src="https://user-images.githubusercontent.com/7291672/184616595-e48cea2d-497f-43d9-988e-36b73ce3a2e6.png">

**Comment by xgqfrms** [comment]
# multi `action.yml` ???

通配符，自动匹配项目根目录下的所有以 `*.yml` 的 GitHub Actions 配置文件？？？


```yml
name: Test
# triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#
jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest
    #
    steps:
      - uses: actions/checkout@v2
      #
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      #
      - name: Install dependencies
        run: npm ci
      #
      - name: Build
        run: npm run build
      # *.yml 文件，自动匹配？
      - name: Run my action
        # ./ 匹配项目根目录下的所有 *.yml ❓
        uses: ./
        # 使用 with 传递参数给 action.yml
        with:
          # name: 'xgqfrms/webgeeker'
          name: 'xgqfrms-github'
          # 关键字 GITHUB_TOKEN, GitHub 会自动注入，无需手动定义该 secrets；✅
          ghToken: ${{secrets.GITHUB_TOKEN}}


```


https://github.com/xgqfrms/github-fe-oss-project-template/runs/7836238134?check_suite_focus=true

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/7291672/184622763-7e54bc5f-2137-4119-af9e-727d09f09d62.png">
